#!/bin/bash

DIRECTORIO=/sys/class/net/wlan0/

if [ -d "$DIRECTORIO" ]
then
	R1=`cat /sys/class/net/wlan0/statistics/rx_bytes`
        T1=`cat /sys/class/net/wlan0/statistics/tx_bytes`
        sleep 1
        R2=`cat /sys/class/net/wlan0/statistics/rx_bytes`
        T2=`cat /sys/class/net/wlan0/statistics/tx_bytes`

else
	R1=`cat /sys/class/net/wlp2s0/statistics/rx_bytes`
	T1=`cat /sys/class/net/wlp2s0/statistics/tx_bytes`
	sleep 1
	R2=`cat /sys/class/net/wlp2s0/statistics/rx_bytes`
	T2=`cat /sys/class/net/wlp2s0/statistics/tx_bytes`
fi


TBPS=`expr $T2 - $T1`
RBPS=`expr $R2 - $R1`
TKBPS=`expr $TBPS / 1024`
RKBPS=`expr $RBPS / 1024`
icon="⬇️"
icon1="⬆️"
printf "%s %s %s %s" "$icon" "$RKBPS kb" "$icon1" "$TKBPS kb"
